In [12]:
import selenium
import pandas as pd
from selenium import webdriver
import time

import warnings
warnings.filterwarnings('ignore')

In [13]:
from selenium.common.exceptions import ElementNotInteractableException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

# Q3 - Guru99 - Pending

In [21]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)

driver.get('https://www.guru99.com/')

WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.CLASS_NAME,'gsc-input')))

product_search = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input')
product_search.send_keys('Selenium Exception handling')

submit_button = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button')
submit_button.click()

WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.CLASS_NAME,'gs-title')))

submit_button = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a')
submit_button.click()

In [22]:
# WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.CLASS_NAME,'table table-striped')))
import time
name = []
desc = []

name =driver.find_elements(By.XPATH,'//table[@class="table table-striped"]/tbody/tr/td[1]')
for i in names:
       name.append(i.text)
name

[]

In [ ]:
x = driver.find_element_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
x.get_attribute('textContent')

In [ ]:
name.get_attribute('textContent')

# Q1 - wikipedia - Completed

In [100]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)

driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [101]:
no = []
name = []
uploader = []
views = []
date = []

for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]'):
    no.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]'):
    name.append(i.text) 
for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]'):
    uploader.append(i.text) 
for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]'):
    views.append(i.text) 
for i in driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]'):
    date.append(i.text) 
    
df = pd.DataFrame({'S.No':no,'Video':name,'Uploader':uploader,'Views':views,'Upload Date':date})
df

,S.No,Video,Uploader,Views,Upload Date
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.95,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.90,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.39,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.76,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.57,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.51,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.72,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.63,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.59,"February 27, 2018"
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,4.50,"January 31, 2012"
10,11.,"""Gangnam Style""[25]",Psy,4.48,"July 15, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.20,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,3.98,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.72,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.61,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,3.61,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,3.56,"October 22, 2015"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.47,"October 7, 2014"
18,19.,"""Axel F""[37]",Crazy Frog,3.42,"June 16, 2009"
19,20.,"""Girls Like You""[38]",Maroon 5,3.31,"May 31, 2018"
20,21.,"""Faded""[39]",Alan Walker,3.31,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,3.30,"February 20, 2014"
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,3.29,"June 25, 2018"
23,24.,"""Let Her Go""[42]",Passenger,3.26,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,3.23,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,3.23,"March 22, 2015"
26,27.,"""Perfect""[45]",Ed Sheeran,3.20,"November 9, 2017"
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,3.19,"June 4, 2010"
28,29.,"""Shake It Off""[47]",Taylor Swift,3.19,"August 18, 2014"
29,30.,"""Mi Gente""[48]",J Balvin,3.10,"June 29, 2017"

# Q4) Statistics Time - Completed

In [128]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)

driver.get('https://www.statisticstimes.com/')

WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.CLASS_NAME,'dropbtn')))

click_button = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
click_button.click()

click_button = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
click_button.click()

# closed ad manually

In [129]:
click_button = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
click_button.click()

In [130]:
rank = []
state = []
gsdp_1920 = []
gsdp_1819 = []
share = []
gdp = []

for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]'):
    if i.text == '':
        rank.append('-')
    else:
        rank.append(i.text)
for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]'):
    if i.text == '':
        state.append('-')
    else:
        state.append(i.text)
for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]'):
    if i.text == '':
        gsdp_1920.append('-')
    else:
        gsdp_1920.append(i.text)        
for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]'):
    if i.text == '':
        gsdp_1819.append('-')
    else:
        gsdp_1819.append(i.text)
for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]'):
    if i.text == '':
        share.append('-')
    else:
        share.append(i.text)
for i in driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]'):
    if i.text == '':
        gdp.append('-')
    else:
        gdp.append(i.text)
        
        
        
print(len(rank),len(state),len(gsdp_1920),len(gsdp_1819),len(share),len(gdp))

33 33 33 33 33 33

In [132]:
df = pd.DataFrame({'Rank':rank,'State':state,'GSDP 19-20':gsdp_1920,'GSDP 18-19':gsdp_1819,'Share(2018)':share,
                  'GSP in $Billion':gdp})
df

,Rank,State,GSDP 19-20,GSDP 18-19,Share(2018),GSP in $Billion
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Q2 - BCCI.tv - Completed

In [51]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')

time.sleep(5)



driver.get('https://www.bcci.tv/')



product_search = driver.find_element_by_xpath('/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')

product_search.click() #clicking on inetrnational tab

driver.execute_script("window.scrollTo(0,750)")

more = driver.find_element_by_xpath('//div[@class="col-lg-12 col-md-12 col-sm-12"]/button')
more.click()

In [52]:
Match = []
Series = []
Place = []
Date = []
Time = []

for i in driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]'):
    Match.append(' '.join(i.text.split()[:-1])) 
    
for i in driver.find_elements_by_xpath('//span[@class="ng-binding"]'):
    Series.append(i.text) 

for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]'):
    Place.append(' '.join(i.text.split()[3:]))

for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
    Date.append(i.text)

for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
    Time.append(i.text)
    
df = pd.DataFrame({'Match Title':Match,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
df

,Match Title,Series,Place,Date,Time
0,3rd ODI,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Old Trafford, Manchester",17 JUL 2022,6:00 AM EDT
1,1st ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad",22 JUL 2022,9:30 AM EDT
2,2nd ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad",24 JUL 2022,9:30 AM EDT
3,3rd ODI,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval, Trinidad",27 JUL 2022,9:30 AM EDT
4,1st T20I,INDIA TOUR OF WEST INDIES T20 SERIES 2022,"Brian Lara Stadium, Trinidad",29 JUL 2022,10:30 AM EDT
5,2nd T20I,INDIA TOUR OF WEST INDIES T20 SERIES 2022,"Warner Park, St Kitts",1 AUG 2022,10:30 AM EDT
6,3rd T20I,INDIA TOUR OF WEST INDIES T20 SERIES 2022,"Warner Park, St Kitts",2 AUG 2022,10:30 AM EDT
7,4th T20I,INDIA TOUR OF WEST INDIES T20 SERIES 2022,Central Broward Regional Park Stadium Turf Gro...,6 AUG 2022,10:30 AM EDT
8,5th T20I,INDIA TOUR OF WEST INDIES T20 SERIES 2022,Central Broward Regional Park Stadium Turf Gro...,7 AUG 2022,10:30 AM EDT

# Q5 - Gitbhub - Completed

In [46]:
from selenium.webdriver.common.action_chains import ActionChains

driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://github.com/')

#hover to explore menu
action = ActionChains(driver)
menu = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]')
action.move_to_element(menu).perform()

# click trending
click_button = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
click_button.click()

In [47]:
repo = []
desc = []
count = []
lang = []

for i in driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]/a'):
    repo.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]'):
    desc.append(i.text)
for i in driver.find_elements_by_xpath('//a[@class="Link--muted d-inline-block mr-3"][2]'):
    count.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="f6 color-fg-muted mt-2"]/span[1]'):
    lang.append(i.text)

df = pd.DataFrame({'Repository':repo,'Description':desc,'Contributors':count,'Language Used':lang})
df['Language Used'] = df['Language Used'].replace(to_replace='Built by', value='-')
df

,Repository,Description,Contributors,Language Used
0,trpc / trpc,🧙‍♀️ Move Fast and Break Nothing. End-to-end t...,273,TypeScript
1,srush / GPU-Puzzles,Solve puzzles. Learn CUDA.,46,Jupyter Notebook
2,apache / shardingsphere,Ecosystem to transform any database into a dis...,"5,750",Java
3,Shopify / sarama,Sarama is a Go library for Apache Kafka.,"1,518",Go
4,microsoft / sbom-tool,The SBOM tool is a highly scalable and enterpr...,23,C#
5,hashicorp / nomad,"Nomad is an easy-to-use, flexible, and perform...","1,608",Go
6,macrozheng / springcloud-learning,一套涵盖大部分核心组件使用的Spring Cloud教程，包括Spring Cloud Al...,"2,343",Java
7,vasanthk / how-web-works,What happens behind the scenes when we type ww...,838,-
8,hackerhouse-opensource / iscsicpl_bypassUAC,UAC bypass for x64 Windows 7 - 11,40,C++
9,near / stakewars-iii,Stake Wars: Episode 3 challenges and place to ...,18,-
10,quickwit-oss / tantivy,Tantivy is a full-text search engine library i...,400,Rust
11,unifyai / ivy,The Unified Machine Learning Framework,"1,043",Python
12,amd64fox / SpotX,Blocking ads and updates for the desktop versi...,63,PowerShell
13,dair-ai / ML-YouTube-Courses,📺 A place to discover the latest machine learn...,875,-
14,tiangolo / fastapi,"FastAPI framework, high performance, easy to l...","3,716",Python
15,github / docs,The open-source repo for docs.github.com,"55,677",JavaScript
16,firebase / firebase-ios-sdk,Firebase iOS SDK,"1,077",Objective-C
17,vuejs / vue,"🖖 Vue.js is a progressive, incrementally-adopt...","32,483",TypeScript
18,jart / cosmopolitan,build-once run-anywhere c library,234,C
19,jwasham / coding-interview-university,A complete computer science study plan to beco...,"60,758",-
20,remix-run / remix,"Build Better Websites. Create modern, resilien...","1,419",TypeScript
21,logto-io / logto,🧑‍🚀 Logto helps you build the sign-in experien...,19,TypeScript
22,ruanyf / weekly,科技爱好者周刊，每周五发布,"1,870",-
23,farcasterxyz / protocol,Specification of the Farcaster Protocol,9,-

# Q9 - IMDB - Completed

In [48]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://www.imdb.com/list/ls095964455/')

In [49]:
Name = []
Year = []
Genre = []
Runtime = []
Ratings = []
Votes = []

for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a'):
    Name.append(i.text)
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]'):
    Year.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="genre"]'):
    Genre.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="runtime"]'):
    Runtime.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]/span[2]'):
    Ratings.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"][3]/span[2]'):
    Votes.append(i.text)
    
df = pd.DataFrame({'Title':Name,'Year':Year,'Genre':Genre,'Runtime':Runtime,'Ratings':Ratings,'Votes':Votes})
df

,Title,Year,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,009,318"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,090,080"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"955,105"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"285,535"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"245,191"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,094"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,891"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"192,238"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,590"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"231,221"

# Q10 UCI Machine Learning Repository - Completed

In [60]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://archive.ics.uci.edu/')

click_button = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a')
click_button.click()

In [72]:
Name = []
datatype = []
task = []
att_type = []
instance = []
att = []
year = []

for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]'):
        Name.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]'):
        datatype.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]'):
        task.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]'):
        att_type.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]'):
        instance.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]'):
        att.append(i.text)
for i in driver.find_elements_by_xpath('//table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]'):
        year.append(i.text)

In [73]:
print(len(Name),len(datatype),len(task),len(att_type),len(instance),len(att),len(year))

623 623 623 623 623 623 623

In [76]:
df = pd.DataFrame({'Name':Name,'Data Type':datatype,'Default Task':task,'Attribut Type':att_type,
                  '# Instance':instance,'# Attribute':att,'Year':year})
df = df.iloc[1: , :]
df

,Name,Data Type,Default Task,Attribut Type,# Instance,# Attribute,Year
1,2.4 GHZ Indoor Channel Measurements,Multivariate,Classification,Real,7840,5,2018
2,"3D Road Network (North Jutland, Denmark)","Sequential, Text","Regression, Clustering",Real,434874,4,2013
3,3W dataset,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
4,9mers from cullpdb,Sequential,"Classification, Regression",Real,158716,4,2021
5,: Simulated Data set of Iraqi tourism places,Multivariate,"Classification, Clustering",,232,16,2020
...,...,...,...,...,...,...,...
618,Youtube cookery channels viewers comments in...,"Multivariate, Text",Classification,,9800,3,2019
619,YouTube Multiview Video Games Dataset,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
620,YouTube Spam Collection,Text,Classification,,1956,5,2017
621,Z-Alizadeh Sani,,Classification,"Integer, Real",303,56,2017
622,Zoo,Multivariate,Classification,"Categorical, Integer",101,17,1990

In [204]:
len(x)

1

# Q8 - The Guardian - Completed

In [247]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [248]:
rank = []
title = []
author = []
sales = []
publisher = []
genre = []

for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[1]'):
    rank.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    title.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]'):
    author.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]'):
    sales.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]'):
    publisher.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]'):
    genre.append(i.text)

df = pd.DataFrame({'Rank':rank,'Title':title,'Auhtor':author,'Sales':sales,'Publisher':publisher,'Genre':genre})
df

,Rank,Title,Auhtor,Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q7 Naukri - Access Denied

In [24]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://www.naukri.com/naukri-dot-com-recruiters')

product_search = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/div/form/div[1]/div/div[1]/div[1]/div[2]/input')
product_search.send_keys('Data Science')

click_button = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/div/form/div[1]/button')
click_button.click()

# Q6 Billboard

In [7]:
driver = webdriver.Chrome(r'C:\Web Driver\chromedriver.exe')
time.sleep(5)
driver.get('https://www.billboard.com/')

# WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.CLASS_NAME,'c-link  lrv-a-unstyle-link lrv-a-unstyle-link lrv-u-color-brand-accent-blue:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-lightest ')))

click_button = driver.find_element_by_xpath('/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
click_button.click()

WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x00996463+2188387]
	Ordinal0 [0x0092E461+1762401]
	Ordinal0 [0x00843D78+802168]
	Ordinal0 [0x00837210+750096]
	Ordinal0 [0x0083675A+747354]
	Ordinal0 [0x00835D3F+744767]
	Ordinal0 [0x00834C28+740392]
	Ordinal0 [0x00835228+741928]
	Ordinal0 [0x0083F153+782675]
	Ordinal0 [0x00849FBB+827323]
	Ordinal0 [0x0084D310+840464]
	Ordinal0 [0x008354F6+742646]
	Ordinal0 [0x00849BF3+826355]
	Ordinal0 [0x0089CF6D+1167213]
	Ordinal0 [0x0088C5F6+1099254]
	Ordinal0 [0x00866BE0+945120]
	Ordinal0 [0x00867AD6+948950]
	GetHandleVerifier [0x00C371F2+2712546]
	GetHandleVerifier [0x00C2886D+2652765]
	GetHandleVerifier [0x00A2002A+520730]
	GetHandleVerifier [0x00A1EE06+516086]
	Ordinal0 [0x0093468B+1787531]
	Ordinal0 [0x00938E88+1805960]
	Ordinal0 [0x00938F75+1806197]
	Ordinal0 [0x00941DF1+1842673]
	BaseThreadInitThunk [0x75F86739+25]
	RtlGetFullPathName_UEx [0x771F8FEF+1215]
	RtlGetFullPathName_UEx [0x771F8FBD+1165]